// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function isLeapYear(year) {
  if (year % 4 !== 0) {
    return false;
  } else {
    return !(year % 100 === 0 && year % 400 !== 0);
  }
}

exports.isLeapYear = isLeapYear;
/* No side effect */
